---

- name: Create dirs for Neutron
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/neutron/plugins/ml2
    - /var/log/neutron
    - /var/lib/neutron

- name: Configure Neutron
  template: src="{{ item }}.j2" dest=/etc/neutron/{{ item }}
  with_items:
    - neutron.conf
    - l3_agent.ini
    - dhcp_agent.ini
    - metadata_agent.ini

- name: Configure Neutron ML2
  template: src="{{ item }}.j2" dest=/etc/neutron/plugins/ml2/{{ item }}
  with_items:
    - ml2_conf.ini

- name: Copy Neutron configuration files
  copy: src="{{ neutron_dir }}/etc/{{ item }}" dest=/etc/neutron/{{ item }} owner={{ global_os_user }}
  with_items:
    - api-paste.ini
    - metering_agent.ini
    - policy.json
    - rootwrap.conf

- name: Sync Neutron database
  command: '/bin/sh -c "{{ neutron_dir }}/venv/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron'
