#- name: Change sysctl.conf
#  lineinfile: dest=/etc/sysctl.conf
#              state=present
#              regexp={{ item.pattern }}
#              line={{ item.string }}
#              backup=yes
#              backrefs=yes
#  with_items:
#    - { pattern: "\#net\.ipv4\.ip_forward=[0,1]", string: "net.ipv4.ip_forward=1" }
#    - { pattern: "\#net\.ipv4\.conf\.all\.rp_filter=[0,1]", string: "net.ipv4.conf.all.rp_filter=0" }
#    - { pattern: "\#net\.ipv4\.conf\.default\.rp_filter=[0,1]", string: "net.ipv4.conf.default.rp_filter=0" }
#  sudo: yes

- name: Change systl.conf
  lineinfile: dest=/etc/sysctl.conf state=present line={{ item }}
  with_items:
    net.ipv4.ip_forward=1
    net.ipv4.conf.all.rp_filter=0
    net.ipv4.conf.default.rp_filter=0
  sudo: yes

- name: Update sysctl
  shell: "sysctl -p"
  sudo: yes

- name: create additional bridge
  openvswitch_bridge: bridge=br-ex state=present
  sudo: yes

- name: create port
  openvswitch_port: bridge=br-ex port=ens256 state=present
  sudo: yes
