---

- name: install psycopg2
  pip: name=psycopg2 virtualenv={{ neutron_dir }}/venv
  when: global_db == "postgresql" and neutron_type == "controller"

#- name: install python-swiftclient
#  pip: name={{ item }} virtualenv={{ glance_dir }}/venv
#  with_items:
#    - python-glanceclient
#    - python-keystoneclient
#    - python-swiftclient
