- name: clone keystone
  git: repo=https://github.com/openstack/keystone.git dest={{ keystone_dir }} clone=yes version={{ openstack_version }}

- name: create virtual env
  command: "virtualenv {{ keystone_dir }}/venv"

- name: install requirements
  pip: requirements={{ keystone_dir }}/requirements.txt virtualenv={{ keystone_dir }}/venv extra_args='--no-cache-dir'

- name: setup.py install
  shell: ". ./venv/bin/activate && python setup.py install"
  args:
    chdir: "{{ keystone_dir }}"
