- name: install MySQL-python
  pip: name=MySQL-python virtualenv={{ keystone_dir }}/venv
  when: global_db == "mysql"

- name: install psycopg2
  pip: name=psycopg2 virtualenv={{ keystone_dir }}/venv
  when: global_db == "postgresql"
