---

- name: Create dir for Cinder
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/cinder
    - /var/log/cinder
    - /var/lib/cinder

- name: Configure Cinder
  template: src="{{ item }}.j2" dest=/etc/cinder/{{ item }}
  with_items:
    - cinder.conf

- name: Copy Cinder configuration files
  copy: src="{{ cinder_dir }}/etc/cinder/{{ item }}" dest="/etc/cinder/{{ item }}" owner={{ global_os_user }}
  with_items:
    - api-httpd.conf
    - logging_sample.conf
    - policy.json
    - api-paste.ini
    - rootwrap.conf
    - rootwrap.d

- name: Sync Cinder database
  command: '/bin/sh -c "{{ cinder_dir }}/venv/bin/cinder-manage db sync" cinder'

- include: configuration_lvm.yml