- name: Clone Cinder
  git: repo=https://github.com/openstack/cinder.git dest={{ cinder_dir }} clone=yes version={{ openstack_version }}

- name: create virtual env
  command: "virtualenv {{ cinder_dir }}/venv"

- name: install requirements
  pip: requirements={{ cinder_dir }}/requirements.txt virtualenv={{ cinder_dir }}/venv extra_args='--no-cache-dir'

- name: setup.py install
  shell: "{{ cinder_dir }}/venv/bin/python {{ cinder_dir }}/setup.py install"
  args:
    chdir: "{{ cinder_dir }}"

- name: copy cinder-rootwrap to /usr/bin
  copy: src={{ cinder_dir }}/venv/bin/cinder-rootwrap
        dest=/usr/bin/cinder-rootwrap
        mode="u+x"
  sudo: yes