---

- name: Create dir for Glance
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/glance
    - /var/log/glance
    - /var/lib/glance

- name: Configure Glance
  template: src="{{ item }}.j2" dest=/etc/glance/{{ item }}
  with_items:
    - glance-api.conf
    - glance-registry.conf

- name: Copy Nova compute config
  copy: src="{{ glance_dir }}/etc/{{ item }}" dest=/etc/glance/{{ item }} owner={{ global_os_user }}
  with_items:
    - glance-api-paste.ini
    - glance-registry-paste.ini
    - policy.json
    - schema-image.json

- name: Sync Glance database
  command: '/bin/sh -c "{{ glance_dir }}/venv/bin/glance-manage db_sync" glance'
