---

- name: Add Ceilometer PPA
  apt_repository: repo="ppa:ubuntu-cloud-archive/{{ openstack_version }}-staging"
                  state=present
                  update_cache=yes
  sudo: yes

- name: Install Ceilometer
  apt: name="{{ item }}" state=present
  with_items:
    - ceilometer-agent-central
    - ceilometer-agent-notification
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
    - python-ceilometerclient
  sudo: yes
  when: ceilometer_type == "controller"

- name: Install Ceilometer
  apt: name="{{ item }}" state=present
  with_items:
    - ceilometer-agent-compute
  sudo: yes
  when: ceilometer_type == "compute"