- name: Clone Horizon
  git: repo=https://github.com/openstack/horizon.git dest={{ horizon_dir }} clone=yes version={{ openstack_version }}

#- name: create virtual env
#  command: "virtualenv {{ horizon_dir }}/venv"

- name: run run_test.sh
  shell: "yes | bash ./run_tests.sh --compilemessages"
  args:
    chdir: "{{ horizon_dir }}"

- name: install requirements
  pip: requirements={{ horizon_dir }}/requirements.txt virtualenv={{ horizon_dir }}/.venv extra_args='--no-cache-dir'

- name: setup.py install
  shell: ". ./.venv/bin/activate && python setup.py install"
  args:
    chdir: "{{ horizon_dir }}"
