---

- name: Create dir for Nova
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/nova
    - /var/log/nova
    - /var/lib/nova

- name: Configure Nova Compute
  template: src=nova.conf.j2
            dest=/etc/nova/nova.conf

- name: Copy api-paste.ini
  copy: src=api-paste.ini dest=/etc/nova/api-paste.ini owner={{ global_os_user }}

- name: Copy rootwrap.conf
  copy: src=rootwrap.conf dest=/etc/nova/rootwrap.conf owner={{ global_os_user }}

- name: Sync Nova database
  command: '/bin/sh -c "{{ nova_dir }}/venv/bin/nova-manage db sync" nova'