---

- name: Create dir for Nova
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/keystone
    - /var/log/keystone

- name: Configure Nova Compute
  template: src=nova.conf.j2
            dest=/etc/nova/nova.conf

- name: Sync Nova database
  command: '/bin/sh -c "{{ keystone_dir }}/venv/bin/nova-manage db_sync" nova'