#- name: install dependencies
#  apt: name="{{ item }}" state=present
#  with_items:
#    - build-essential
#    - libssl-dev
#    - libffi-dev
#    - python-dev
#    - libmariadbclient-dev
#    - git
#  sudo: yes

#- name: download pip installation script
#  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~
#  sudo: yes
#- name: install pip
#  command: "python ~/get-pip.py"
#  sudo: yes

- name: clone keystone
  git: repo=https://github.com/openstack/nova.git dest={{ nova_dir }} clone=yes

- name: install virtualenv
  pip: name=virtualenv
  sudo: yes

- name: create virtual env
  command: "virtualenv {{ nova_dir }}/venv"

- name: install requirements
  pip: requirements={{ nova_dir }}/requirements.txt virtualenv={{ nova_dir }}/venv extra_args='--no-cache-dir'

- name: setup.py install
  shell: "{{ nova_dir }}/venv/bin/python {{ nova_dir }}/setup.py install"
  args:
    chdir: "{{ nova_dir }}"
