- name: Create user and database
  shell: "mongo --host controller --eval ' db = db.getSiblingDB(\"{{ db_name }}\"); db.addUser({user: \"{{ db_user }}\", pwd: \"{{ user_pass }}\", roles: [ \"readWrite\", \"dbAdmin\" ]})'"