---

- name: Create dir for Nova
  file: path={{ item }} state=directory mode=0755 owner={{ global_os_user }}
  sudo: yes
  with_items:
    - /etc/nova
    - /var/log/nova
    - /var/lib/nova

- name: Configure Nova
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf

- name: Copy Nova compute configuration files
  copy: src=nova-compute.conf dest=/etc/nova/nova-compute.conf owner={{ global_os_user }}
  when: nova_type == "compute"

- name: Copy Nova controller configuration files
  copy: src="{{ nova_dir }}/etc/nova/{{ item }}" dest="/etc/nova/{{ item }}" owner={{ global_os_user }}
  with_items:
    - rootwrap.conf
    - rootwrap.d
  when: nova_type == "controller"

- name: Copy Nova common configuration files
  copy: src="{{ nova_dir }}/etc/nova/{{ item }}" dest="/etc/nova/{{ item }}" owner={{ global_os_user }}
  with_items:
    - api-paste.ini
    - policy.json
    - logging_sample.conf

- name: Sync Nova database
  command: '/bin/sh -c "{{ nova_dir }}/venv/bin/nova-manage db sync" nova'
  when: nova_type == "controller"

- name: Change owners
  shell: "chown -R {{ global_os_user }}:{{ global_os_user }} /var/run/libvirt"
  sudo: yes
  when: nova_type == "compute"