- name: Clone Swift
  git: repo=https://github.com/openstack/swift.git dest={{ swift_dir }} clone=yes

- name: create virtual env
  command: "virtualenv {{ swift_dir }}/venv"

- name: install requirements
  pip: requirements={{ swift_dir }}/requirements.txt virtualenv={{ swift_dir }}/venv extra_args='--no-cache-dir'

- name: setup.py install
  shell: "{{ swift_dir }}/venv/bin/python {{ swift_dir }}/setup.py install"
  args:
    chdir: "{{ swift_dir }}"
