---

- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
  sudo: yes

- name: Install PostgreSQL dependencies
  apt: name={{ item }}
  with_items:
    - libpq-dev
  sudo: yes
  when: global_db == "postgresql"

- name: Install MariaDB dependencies
  apt: name={{ item }}
  with_items:
    - libmariadbclient-dev
  sudo: yes
  when: global_db == "mysql"

- name: download pip installation script
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~
  sudo: yes

- name: install pip
  command: "python ~/get-pip.py"
  sudo: yes

- name: install virtualenv
  pip: name=virtualenv
  sudo: yes