---

controller_ip: 127.0.0.1
my_ip: 127.0.0.1

# Glance
cinder_log_dir: /var/log/cinder
cinder_default_region: RegionOne
cinder_dir: /tmp/cinder
cinder_rabbitmq_ip: 127.0.0.1
cinder_rabbitmq_user: openstack
cinder_rabbitmq_password: tester

# Keystone
cinder_auth_username: cinder
cinder_auth_password: tester

# Database
cinder_database_url: sqlite:////var/lib/cinder/cinder.db
