---

- hosts: all

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes
    - lineinfile: dest=/etc/sudoers
                  regexp="^\s*Defaults\s+secure_path"
                  line='Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/lib/udev"'
      sudo: yes
    - lineinfile: dest=/etc/environment
                  regexp="^\s*PATH"
                  line='PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/lib/udev"'
      sudo: yes

  roles:
    - role: common_dependencies

    - role: postgresql
      postgresql_admin_user: "postgres"

    - role: openstack-nova
      nova_dir: /home/{{ global_os_user }}/nova
      nova_database_url: "{{ global_db }}://nova:{{ global_nova_password }}@localhost/nova"
      nova_neutron_url: "{{ global_controller_ip }}"
      nova_admin_auth_url: "http://{{ global_controller_ip }}:35357/v2.0"
      nova_type: "compute"
      neutron_auth_username: "{{ global_neutron_user }}"
      neutron_auth_password: "{{ global_neutron_password }}"
      controller_ip: "{{ global_controller_ip }}"
      my_ip: "{{ global_my_ip }}"
      nova_rabbitmq_ip: "{{ global_controller_ip }}"
      nova_rabbitmq_user: "{{ global_rabbitmq_user }}"
      nova_rabbitmq_password: "{{ global_rabbitmq_password }}"
      openstack_version: "stable/liberty"
      nova_novnc_public_ip: "{{ global_controller_management_ip }}"
      nova_glance_ip: "{{ global_glance_ip }}"
      metadata_secret: "{{ global_metadata_secret }}"

    - role: openstack-neutron
      neutron_dir: /home/{{ global_os_user }}/neutron
      neutron_database_url: "{{ global_db }}://neutron:{{ global_neutron_password }}@localhost/neutron"
      controller_ip: "{{ global_controller_ip }}"
      my_ip: "{{ global_my_ip }}"
      neutron_auth_username: "{{ global_neutron_user }}"
      neutron_auth_password: "{{ global_neutron_password }}"
      nova_auth_username: "{{ global_nova_user }}"
      nova_auth_password: "{{ global_nova_password }}"
      neutron_rabbitmq_ip: "{{ global_controller_ip }}"
      neutron_rabbitmq_user: "{{ global_rabbitmq_user }}"
      neutron_rabbitmq_password: "{{ global_rabbitmq_password }}"
      neutron_type: "{{ global_deploy_type }}"
      openstack_version: "stable/liberty"
      metadata_secret: "{{ global_metadata_secret }}"

    - role: openstack-ceilometer
      ceilometer_dir: /home/{{ global_os_user }}/ceilometer
      controller_ip: "{{ global_controller_ip }}"
      ceilometer_type: compute
      ceilometer_database_url: "{{ global_db }}://mongodb:{{ global_ceilometer_password }}@localhost/ceilometer"
      ceilometer_auth_username: "{{ global_ceilometer_user }}"
      ceilometer_auth_password: "{{ global_ceilometer_password }}"
      ceilometer_rabbitmq_ip: "{{ global_controller_ip }}"
      ceilometer_rabbitmq_user: "{{ global_rabbitmq_user }}"
      ceilometer_rabbitmq_password: "{{ global_rabbitmq_password }}"
      openstack_version: liberty
