---

- hosts: test_host

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes
    - lineinfile: dest=/etc/sudoers regexp="^\s*Defaults\s+env_reset" state=absent
      sudo: yes
    - lineinfile: dest=/etc/sudoers
                  regexp="^\s*Defaults\s+secure_path"
                  line='Defaults env_keep = "PATH VIRTUAL_ENV"'
      sudo: yes

  roles:
    - role: common_dependencies

    - role: postgresql
      postgresql_admin_user: "postgres"
      postgresql_databases: [nova, keystone, neutron]
      postgresql_users:
        - { name: nova, pass: "{{ global_nova_password }}" }
        - { name: keystone, pass: "{{ global_keystone_password }}" }
        - { name: neutron, pass: "{{ global_neutron_password }}" }
      postgresql_user_privileges:
        - { role: nova, db: nova }
        - { role: keystone, db: keystone }
        - { role: neutron, db: neutron }

    - role: openstack-keystone
      keystone_dir: /home/{{ global_os_user }}/keystone
      keystone_part: server
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_database_url: "{{ global_db }}://keystone:{{ global_keystone_password }}@localhost/keystone"
      openstack_version: "stable/liberty"

    - role: openstack-keystone
      keystone_hostname: "{{ global_controller_ip }}"
      keystone_part: client
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_admin_port: 35357
      keystone_port: 5000
      keystone_tenants:
        - { name: admin, description: "Admin tenant" }
        - { name: service, description: "Service tenant" }
        - { name: demo, description: "Demo tenant" }
      keystone_users:
        - { name: "{{ global_keystone_user }}", password: "{{ global_keystone_password }}", tenant: admin }
        - { name: demo, password: "{{ global_keystone_password }}", tenant: demo }
        - { name: "{{ global_nova_user }}", password: "{{ global_nova_password }}", tenant: service }
        - { name: "{{ global_neutron_user }}", password: "{{ global_neutron_password }}", tenant: service }
        - { name: "{{ global_glance_user }}", password: "{{ global_glance_password }}", tenant: service }
        - { name: "{{ global_cinder_user }}", password: "{{ global_cinder_password }}", tenant: service }
        - { name: "{{ global_swift_user }}", password: "{{ global_swift_password }}", tenant: service }
        - { name: "{{ global_ceilometer_user }}", password: "{{ global_ceilometer_password }}", tenant: service }
      keystone_roles:
        - { name: admin, user: admin, tenant: admin }
        - { name: demo, user: demo, tenant: demo }
        - { name: admin, user: "{{ global_nova_user }}", tenant: service }
        - { name: admin, user: "{{ global_neutron_user }}", tenant: service }
        - { name: admin, user: "{{ global_glance_user }}", tenant: service }
        - { name: admin, user: "{{ global_cinder_user }}", tenant: service }
        - { name: admin, user: "{{ global_swift_user }}", tenant: service }
        - { name: admin, user: "{{ global_ceilometer_user }}", tenant: service }
      keystone_services:
        - { name: keystone, service_type: identity }
        - { name: nova, service_type: compute }
        - { name: neutron, service_type: network }
        - { name: glance, service_type: image }
        - { name: cinder, service_type: volume }
        - { name: cinderv2, service_type: volumev2 }
        - { name: sahara, service_type: data-processing }
        - { name: swift, service_type: object-store }
        - { name: ceilometer, service_type: metering }
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://{{ global_my_ip }}:5000/v2.0"
          internal_url: "http://{{ global_my_ip }}:5000/v2.0"
          admin_url: "https://{{ global_public_name }}:35357/v2.0"
          region: RegionOne
        - service_name: nova
          public_url: "http://{{ global_my_ip }}:8774/v2/%(tenant_id)s"
          internal_url: "http://{{ global_my_ip }}:8774/v2/%(tenant_id)s"
          admin_url: "http://{{ global_public_name }}:8774/v2/%(tenant_id)s"
          region: RegionOne
        - service_name: neutron
          public_url: "http://{{ global_my_ip }}:9696"
          internal_url: "http://{{ global_my_ip }}:9696"
          admin_url: "http://{{ global_public_name }}:9696"
          region: RegionOne
        - service_name: glance
          public_url: "http://{{ global_glance_ip }}:9292"
          internal_url: "http://{{ global_glance_ip }}:9292"
          admin_url: "http://{{ global_public_name }}:9292"
          region: RegionOne
        - service_name: cinder
          public_url: "http://{{ global_glance_ip }}:8776/v2/%(tenant_id)s"
          internal_url: "http://{{ global_glance_ip }}:8776/v2/%(tenant_id)s"
          admin_url: "http://{{ global_public_name }}:8776/v2/%(tenant_id)s"
          region: RegionOne
        - service_name: cinderv2
          public_url: "http://{{ global_glance_ip }}:8776/v2/%(tenant_id)s"
          internal_url: "http://{{ global_glance_ip }}:8776/v2/%(tenant_id)s"
          admin_url: "http://{{ global_public_name }}:8776/v2/%(tenant_id)s"
          region: RegionOne
        - service_name: sahara
          public_url: "http://{{ global_glance_ip }}:8386/v1.1/%(tenant_id)s"
          internal_url: "http://{{ global_glance_ip }}:8386/v1.1/%(tenant_id)s"
          admin_url: "http://{{ global_public_name }}:8386/v1.1/%(tenant_id)s"
          region: RegionOne
        - service_name: swift
          public_url: "http://{{ global_swift_ip }}:8080/v1/AUTH_%(tenant_id)s"
          internal_url: "http://{{ global_swift_ip }}:8080/v1/AUTH_%(tenant_id)s"
          admin_url: "http://{{ global_public_name }}:8080/v1"
          region: RegionOne
        - service_name: ceilometer
          public_url: "http://{{ global_ceilometer_ip }}:8777"
          internal_url: "http://{{ global_ceilometer_ip }}:8777"
          admin_url: "http://{{ global_public_name }}:8777"
          region: RegionOne

    - role: openstack-nova
      nova_dir: /home/{{ global_os_user }}/nova
      nova_database_url: "{{ global_db }}://nova:{{ global_nova_password }}@localhost/nova"
      my_ip: "{{ global_my_ip }}"
      controller_ip: "{{ global_controller_ip }}"
      nova_type: "controller"
      nova_auth_username: "{{ global_nova_user }}"
      nova_auth_password: "{{ global_nova_password }}"
      nova_rabbitmq_ip: "{{ global_my_ip }}"
      nova_rabbitmq_user: "{{ global_rabbitmq_user }}"
      nova_rabbitmq_password: "{{ global_rabbitmq_password }}"
      nova_neutron_url: "http://{{ global_controller_ip }}:9696"
      nova_admin_auth_url: "http://{{ global_controller_ip }}:35357/v2.0"
      nova_glance_ip: "{{ global_glance_ip }}"
      neutron_auth_username: "{{ global_neutron_user }}"
      neutron_auth_password: "{{ global_neutron_password }}"
      openstack_version: "stable/liberty"
      nova_novnc_public_ip: "{{ global_controller_management_ip }}"
      metadata_secret: "{{ global_metadata_secret }}"

    - role: openstack-horizon
      horizon_dir: /home/{{ global_os_user }}/horizon
      controller_ip: "{{ global_controller_ip }}"
      my_ip: "{{ global_my_ip }}"
      openstack_version: "stable/liberty"

    - role: openstack-neutron
      neutron_dir: /home/{{ global_os_user }}/neutron
      neutron_database_url: "{{ global_db }}://neutron:{{ global_neutron_password }}@localhost/neutron"
      controller_ip: "{{ global_controller_ip }}"
      my_ip: "{{ global_my_ip }}"
      neutron_auth_username: "{{ global_neutron_user }}"
      neutron_auth_password: "{{ global_neutron_password }}"
      nova_auth_username: "{{ global_nova_user }}"
      nova_auth_password: "{{ global_nova_password }}"
      neutron_rabbitmq_ip: "{{ global_controller_ip }}"
      neutron_rabbitmq_user: "{{ global_rabbitmq_user }}"
      neutron_rabbitmq_password: "{{ global_rabbitmq_password }}"
      neutron_type: "{{ global_deploy_type }}"
      openstack_version: "stable/liberty"
      metadata_secret: "{{ global_metadata_secret }}"

