---

- hosts: all

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes

  roles:
    - role: common_dependencies

    - role: postgresql
      postgresql_admin_user: "postgres"
      postgresql_databases: [nova, keystone]
      postgresql_users:
        - { name: nova, pass: "{{ global_nova_password }}" }
        - { name: keystone, pass: "{{ global_keystone_password }}" }
      postgresql_user_privileges:
        - { role: nova, db: nova }
        - { role: keystone, db: keystone }

    - role: openstack-keystone
      keystone_dir: /home/{{ global_os_user }}/keystone
      keystone_database_url: "{{ global_db }}://keystone:{{ global_keystone_password }}@localhost/keystone"
      keystone_admin_token: "{{ global_keystone_token }}"
      keystone_admin_port: 35357
      keystone_port: 5000
      keystone_tenants:
        - { name: admin, description: "Admin tenant" }
        - { name: service, description: "Service tenant" }
        - { name: demo, description: "Demo tenant" }
      keystone_users:
        - { name: "{{ global_keystone_user }}", password: "{{ global_keystone_password }}", tenant: admin }
        - { name: demo, password: "{{ global_keystone_password }}", tenant: demo }
        - { name: "{{ global_nova_user }}", password: "{{ global_nova_password }}", tenant: service }
      keystone_roles:
        - { name: admin, user: admin, tenant: admin }
        - { name: demo, user: demo, tenant: demo }
        - { name: admin, user: "{{ global_nova_user }}", tenant: service }
      keystone_services:
        - { name: keystone, service_type: identity }
        - { name: nova, service_type: compute }
      keystone_endpoints:
        - service_name: keystone
          public_url: "http://127.0.0.1:5000/v2.0"
          internal_url: "http://127.0.0.1:5000/v2.0"
          admin_url: "http://127.0.0.1:35357/v2.0"
        - service_name: nova
          public_url: "http://127.0.0.1:8774/v2/%(tenant_id)s"
          internal_url: "http://127.0.0.1:8774/v2/%(tenant_id)s"
          admin_url: "http://127.0.0.1:8774/v2/%(tenant_id)s"

    - role: openstack-nova
      nova_dir: /home/{{ global_os_user }}/nova
      nova_database_url: "{{ global_db }}://nova:{{ global_nova_password }}@localhost/nova"
      nova_type: "controller"
