---

- hosts: all

  roles:
    - role: client-environment
      controller_ip: http://127.0.0.1:35357
      username: "{{ global_keystone_user }}"
      password: "{{ global_keystone_password }}"
      tenant: "{{ global_keystone_tenant }}"
      script_dir: /tmp

    - role: management-scripts
      nova_dir: "/home/{{ global_os_user }}/nova"
      deploy_type: "{{ global_deploy_type }}"
      glance_dir: "/home/{{ global_os_user }}/glance"
      neutron_dir: "/home/{{ global_os_user }}/neutron"
      horizon_dir: "/home/{{ global_os_user }}/horizon"
      horizon_address: 0.0.0.0:9000
      script_dir: /tmp