---

- hosts: test_host

  roles:
    - role: common_dependencies

    - role: client-environment
      controller_ip: http://127.0.0.1:35357
      username: "{{ global_keystone_user }}"
      password: "{{ global_keystone_password }}"
      tenant: "{{ global_keystone_tenant }}"
      client_dir: "/home/{{ global_os_user }}/clients"

    - role: management-scripts
      nova_dir: "/home/{{ global_os_user }}/nova"
      deploy_type: "{{ global_deploy_type }}"
      glance_dir: "/home/{{ global_os_user }}/glance"
      neutron_dir: "/home/{{ global_os_user }}/neutron"
      horizon_dir: "/home/{{ global_os_user }}/webui"
      keystone_dir: "/home/{{ global_os_user }}/keystone"
      horizon_address: 0.0.0.0:9000
      script_dir: "/home/{{ global_os_user }}/clients"