---

- hosts: all

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes

  roles:
    - role: common_dependencies

    - role: postgresql
      postgresql_admin_user: "postgres"
      postgresql_databases: [glance, cinder]
      postgresql_users:
        - { name: glance, pass: "{{ global_glance_password }}" }
        - { name: cinder, pass: "{{ global_cinder_password }}" }
      postgresql_user_privileges:
        - { role: glance, db: glance }
        - { role: cinder, db: cinder }

    - role: openstack-glance
      glance_dir: /home/{{ global_os_user }}/glance
      glance_database_url: "{{ global_db }}://glance:{{ global_glance_password }}@localhost/glance"
      controller_ip: "{{ global_controller_ip }}"
      glance_auth_username: "{{ global_glance_user }}"
      glance_auth_password: "{{ global_glance_password }}"
      openstack_version: "stable/liberty"

    - role: openstack-cinder
      cinder_dir: /home/{{ global_os_user }}/cinder
      cinder_database_url: "{{ global_db }}://cinder:{{ global_cinder_password }}@localhost/cinder"
      controller_ip: "{{ global_controller_ip }}"
      cinder_auth_username: "{{ global_cinder_user }}"
      cinder_auth_password: "{{ global_cinder_password }}"
      my_ip: "{{ global_my_ip }}"
      cinder_rabbitmq_ip: "{{ global_controller_ip }}"
      cinder_rabbitmq_user: "{{ global_rabbitmq_user }}"
      cinder_rabbitmq_password: "{{ global_rabbitmq_password }}"
      openstack_version: "stable/liberty"

#    - role: openstack-swift
#      swift_dir: /home/{{ global_os_user }}/swift
#      controller_ip: "{{ global_controller_ip }}"
#      swift_auth_username: "swift"
#      swift_auth_password: "tester"
#      my_ip: "{{ global_my_ip }}"
#
#    - role: client
#      controller_ip: "http://{{ global_controller_ip }}:35357/v2.0"
#      username: "admin"
#      password: "tester"
#      client_dir: "/home/{{ global_os_user }}"
