---

- hosts: all

  pre_tasks:
    - apt: update_cache=yes
      sudo: yes
    - apt: name=git state=present
      sudo: yes
    - lineinfile: dest=/etc/sudoers regexp="^\s*Defaults\s+env_reset" state=absent
      sudo: yes
    - lineinfile: dest=/etc/sudoers
                  regexp="^\s*Defaults\s+secure_path"
                  line='Defaults env_keep = "PATH VIRTUAL_ENV"'
      sudo: yes

  roles:
    - role: common_dependencies

    - role: postgresql
      postgresql_admin_user: "postgres"
      postgresql_databases: [glance, cinder, sahara]
      postgresql_users:
        - { name: glance, pass: "{{ global_glance_password }}" }
        - { name: cinder, pass: "{{ global_cinder_password }}" }
        - { name: sahara, pass: "{{ global_sahara_password }}" }
      postgresql_user_privileges:
        - { role: glance, db: glance }
        - { role: cinder, db: cinder }
        - { role: sahara, db: sahara }

    - role: openstack-glance
      glance_dir: /home/{{ global_os_user }}/glance
      glance_database_url: "{{ global_db }}://glance:{{ global_glance_password }}@localhost/glance"
      controller_ip: "{{ global_controller_ip }}"
      glance_auth_username: "{{ global_glance_user }}"
      glance_auth_password: "{{ global_glance_password }}"
      openstack_version: "stable/liberty"

    - role: openstack-cinder
      cinder_dir: /home/{{ global_os_user }}/cinder
      cinder_database_url: "{{ global_db }}://cinder:{{ global_cinder_password }}@localhost/cinder"
      controller_ip: "{{ global_controller_ip }}"
      cinder_auth_username: "{{ global_cinder_user }}"
      cinder_auth_password: "{{ global_cinder_password }}"
      my_ip: "{{ global_my_ip }}"
      cinder_rabbitmq_ip: "{{ global_controller_ip }}"
      cinder_rabbitmq_user: "{{ global_rabbitmq_user }}"
      cinder_rabbitmq_password: "{{ global_rabbitmq_password }}"
      cinder_glance_ip: "{{ global_glance_ip }}"
      openstack_version: "stable/liberty"

    - role: openstack-sahara
      sahara_dir: /home/{{ global_os_user }}/sahara
      sahara_database_url: "{{ global_db }}://sahara:{{ global_sahara_password }}@localhost/sahara"
      controller_ip: "{{ global_controller_ip }}"
      sahara_auth_username: "{{ global_sahara_user }}"
      sahara_auth_password: "{{ global_sahara_password }}"
      openstack_version: "stable/liberty"
      public_name: "{{ global_public_name }}"
