# file: postgresql/tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: PostgreSQL | Create users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
    login_password: "{{ global_postgresql_password }}"
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  with_items: postgresql_users
#    - { name: 'keystone', password: '{{ global_keystone_password }}' }
#    - { name: 'nova', password: '{{ global_nova_password }}' }